"""
For structured outputs we need to define the schema of the output. Define them here for keyword agent.
"""
from typing import Literal
from pydantic import BaseModel, Field

class Entities(BaseModel):
    """
    Represents the extracted entities from the user input.
    """
    entities: list[str] = Field(
        ...,
        description="List of 3 extracted entities from the user input.",
    )

class RouteToQueryOrAnalysis(BaseModel):
    """
    Represents the routing decision based on the tool response.
    """
    route: Literal["query_generator", "competitor_analysis"] = Field(
        ...,
        description="Routing decision: either 'query_generator' or 'competitor_analysis'.",
    )

class SearchQueries(BaseModel):
    """
    Represent the generated search queries based on the extracted entities and user input.
    """
    search_queries: list[str] = Field(
        ...,
        description= "List of 2 generated search queries based on the extracted entities and user input.",
    )

class WebSearchResult(BaseModel):
    """
    Represents a single web search result.
    """
    rank: int = Field(
        ...,
        description="Rank of the search result based on relevance and quality of competition. 1 is the highest rank",
    )
    url: str = Field(
        ...,
        description="URL of the web page",
    )
    title: str = Field(
        ...,
        description="Title of the web page",
    )
    published_date: str = Field(
        ...,
        description="Published date of the web page",
    )
    highlights: str = Field(
        ...,
        description="Highlights of text content from the web page",
    )

class CompetitorAnalysisOutputModel(BaseModel):
    """
    Represents the output of the competitor analysis model.
    """
    search_queries: list[str] = Field(
        ...,
        description="List of top 2 search queries that gave the best web search results.",
    )
    web_search_results: list[WebSearchResult] = Field(
        ...,
        description="List of top 5 web search results obtained from the competitor analysis.",
    )
    competitive_analysis: str = Field(
        ...,
        description="The competitive analysis generated by the model.",
    )