"""
Define the state for the Keyword Agent here.
"""
from typing import Any
from langgraph.graph import MessagesState


class KeywordState(MessagesState):
    # user input: draft article
    user_input: str

    # output from step 1: list of retrieved entities and events from user input
    retrieved_entities: list[str]

    # output from step 2: agent generated search queries to find competitors based on retrieved entities
    generated_search_queries: list[str]
    tool_call_count: int
    web_search_results_accumulated: str

    # output from step 3: executing search queries: index = rank, dict[str, Any] = tavily/exa parsed response
    competitor_information: list[dict[str, Any]]

    # output from step 4: competitive analysis generated by our agent after comparing our article with competitor content
    competitive_analysis: str

    # output from step 5: google keyword planner data
    keyword_planner_data: list[dict[str, Any]]

    # output from step 6: refined keyword masterlist (sorted descending)
    keyword_masterlist: list[dict[str, str]]

    # output from step 7: primary keywords to use in the article: list of objects, each object dict[str, str] = {key=keyword, value=reasoning}
    primary_keywords: list[dict[str, str]]
    secondary_keywords: list[dict[str, str]]

    # output from step 8: final answer with complete suggestions and reasoning
    suggested_url_slug: str
    suggested_article_headlines: list[str]
    final_answer: str
    